//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientRequests
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClientRequests()
        {
            this.DoneRequests = new HashSet<DoneRequests>();
        }
    
        public int Id { get; set; }
        public int CarId { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public string Description { get; set; }
        public bool Done { get; set; }
    
        public virtual ClientCars ClientCars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DoneRequests> DoneRequests { get; set; }
    }
}
