//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostServices
    {
        public int Id { get; set; }
        public int Post { get; set; }
        public int Service { get; set; }
    
        public virtual Posts Posts { get; set; }
        public virtual Service Service1 { get; set; }
    }
}
