//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GEntities : DbContext
    {
        public GEntities()
            : base("name=GEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AvailableDetails> AvailableDetails { get; set; }
        public virtual DbSet<BodyTypes> BodyTypes { get; set; }
        public virtual DbSet<CarModels> CarModels { get; set; }
        public virtual DbSet<CarStamps> CarStamps { get; set; }
        public virtual DbSet<ClientCars> ClientCars { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Colours> Colours { get; set; }
        public virtual DbSet<Deliviries> Deliviries { get; set; }
        public virtual DbSet<Details> Details { get; set; }
        public virtual DbSet<EngineLocation> EngineLocation { get; set; }
        public virtual DbSet<Engines> Engines { get; set; }
        public virtual DbSet<EngineTypes> EngineTypes { get; set; }
        public virtual DbSet<EngineVolume> EngineVolume { get; set; }
        public virtual DbSet<FuelTypes> FuelTypes { get; set; }
        public virtual DbSet<GearboxTypes> GearboxTypes { get; set; }
        public virtual DbSet<Genders> Genders { get; set; }
        public virtual DbSet<LoginData> LoginData { get; set; }
        public virtual DbSet<ManufacturerCountry> ManufacturerCountry { get; set; }
        public virtual DbSet<Posts> Posts { get; set; }
        public virtual DbSet<PostServices> PostServices { get; set; }
        public virtual DbSet<Provider> Provider { get; set; }
        public virtual DbSet<Service> Service { get; set; }
        public virtual DbSet<ServiceDetails> ServiceDetails { get; set; }
        public virtual DbSet<Store> Store { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TechnicalInformation> TechnicalInformation { get; set; }
        public virtual DbSet<Workers> Workers { get; set; }
        public virtual DbSet<Works> Works { get; set; }
    }
}
