//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class TechnicalInformation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TechnicalInformation()
        {
            this.CarModels = new HashSet<CarModels>();
        }
    
        public int Id { get; set; }
        public int BodyType { get; set; }
        public int PlaceCount { get; set; }
        public int DoorCount { get; set; }
        public int EngineLocation { get; set; }
        public int GearboxType { get; set; }
        public int Engine { get; set; }
    
        public virtual BodyTypes BodyTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarModels> CarModels { get; set; }
        public virtual EngineLocation EngineLocation1 { get; set; }
        public virtual Engines Engines { get; set; }
        public virtual GearboxTypes GearboxTypes { get; set; }
    }
}
