//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Works
    {
        public int Id { get; set; }
        public int Car { get; set; }
        public int Service { get; set; }
        public int Worker { get; set; }
        public System.DateTime StartDate { get; set; }
        public string StartTime { get; set; }
        public System.DateTime ExDate { get; set; }
        public string ExTime { get; set; }
    
        public virtual ClientCars ClientCars { get; set; }
        public virtual Service Service1 { get; set; }
        public virtual Workers Workers { get; set; }
    }
}
